[package]
name = "jokai"
version = "0.1.0"
authors = ["Yutaka Furukawa <frkw@fuse.co.jp>"]
edition = "2024"
build = "build.rs"

[dependencies]
axum = { version = "0.8.1", features = ["multipart"] }
base64 = "0.22.1"
clap = { version = "4.5.38", features = ["derive", "env"] }
color-eyre = "0.6.5"
chrono = "0.4.40"
include_dir = "0.7.4"
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["macros", "rt-multi-thread", "signal"] }
tokio-postgres = "0.7.13"
tracing = "0.1.44"
tracing-error = "0.2.1"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
url = "2.5.4"

[build-dependencies]
chrono = "0.4.40"

[dev-dependencies]
assert_cmd = "2.0.17"
